### PR TITLE
Improve messages for syntax errors

### PR DESCRIPTION
**Pull request by toupeira**
Follow-up to #205, I used the opportunity to get my feet wet with ExUnit :)

### CODE REVIEW

**Comment by toupeira** [comment]
Build is failing on Elixir 1.0 because of different error messages, let me know if you still want to support that and I'll take a look.

**Comment by lpil** [comment]
Yes, I would like to support 1.0, thank you :)

**Comment by toupeira** [comment]
Looks like I ran into https://github.com/elixir-lang/elixir/issues/2993, I updated `script_test.exs` accordingly.

**Comment by lpil** [comment]
Great! Thank you :)

**Pull request merged**
