### PR TITLE
Replace probably_* functions with decisivei ones

### PR DESCRIPTION
**Pull request by rrrene**
So probably_snake_case? becomes snake_case? and so on ...

Discussed here: https://github.com/lpil/dogma/issues/117

### CODE REVIEW

**Comment by lpil** [comment]
Thanks! :)

**Comment by lpil** [comment]
Dogma seems to be failing now.

```
Inspecting 97 files.

.........................................................X.......................................

97 files, 1 error!

== test/dogma/script_sources_test.exs ==
54: VariableName: Variable names should be in snake_case
```

**Comment by rrrene** [comment]
Yeah, it was, but not because of the `snake_case?` test. It was failing because the VariableName rule was not working correctly. 

Add this code to a test using the current master and it will pass:

    [
      %ScriptSource{some_field: someVariable}
    ] = anotherVar

The functionality in the Name module works correctly and I tried my best to fix the rule for now, but discovered deeper issues with the VariableName rule in the process. 

The most prominent one is that we stop to discover errors in an AST-Node when we find the first one (due to the use of `Enum.all?`). We also get wrong line numbers with the sample code above.

Maybe I will try to find a solution for this next week, but at least this PR should now be fixed.

**Comment by lpil** [comment]
Thanks :)

Did you open an issue for this bug?

**Comment by rrrene** [comment]
I opened an issue for it!

**Comment by lpil** [comment]
Thanks

**Pull request merged**
