### PR TITLE
Test more elixir versions using travis

### PR DESCRIPTION
**Pull request by meadsteve**
Including 1.1.0 & otp 18

### CODE REVIEW

**Comment by meadsteve** [comment]
@lpil looks like there's some changes in elixir 1.1.0 that break some of the dogma rules,

**Comment by lpil** [comment]
Rebase please :)

**Comment by meadsteve** [comment]
@lpil re-based but this will still be a broken build :smile:

**Comment by lpil** [comment]
I think travis is broken again.

**Comment by meadsteve** [comment]
Closing in favour of #127

**Pull request closed without merging**
