### PR TITLE
Update travis test dependencies

### PR DESCRIPTION
**Pull request by timbuchwaldt**

### CODE REVIEW

**Comment by timbuchwaldt** [comment]
So - this works for Elixir 1.1.0 now  (although a bit hacky). Do you want to still support 1.0.x, @lpil ? 
I would otherwise refactor this a bit. Supporting 1.0.x probably needs some more magic pattern matching to detect the new output of tokenize.

**Comment by timbuchwaldt** [comment]
Haha nice. Should have checked the other PRs first m(

**Comment by lpil** [comment]
Oh dear. I guess this is what we get for making bits of the compiler hard dependencies... ;)

I've not had time to look into this, but we'll find a resolution soon. I'd like to maintain compatibility with all supported versions of Elixir.

**Comment by lpil** [comment]
@rrrene fixed it before I even got to a computer! :dancer: 

Could you rebase please?

**Pull request closed without merging**
